pipeline {
  agent { docker { image 'emeraldsquad/sonar-scanner:latest' } }
  stages {
    stage('build && SonarQube analysis') {
      steps {
        withSonarQubeEnv('sonar.tools.devops.****') {
          sh 'sonar-scanner \\ -Dsonar.projectKey=flaskApp \\ -Dsonar.sources=./src \\'
        }
      }
    }
    stage("Quality Gate") {
      steps {
        timeout(time: 1, unit: 'HOURS') {
          // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
          // true = set pipeline to UNSTABLE, false = don't
          // Requires SonarScanner for Jenkins 2.7+
          waitForQualityGate abortPipeline: true
        }
      }
    }
  }
}
